// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyoFEZfAdjWhSZ-viLaBXGjb4OUr7_XH4',
    appId: '1:99718845829:web:ea5b93cc1ef35f0d4ba0ec',
    messagingSenderId: '99718845829',
    projectId: 'jeevan-b42a9',
    authDomain: 'jeevan-b42a9.firebaseapp.com',
    storageBucket: 'jeevan-b42a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChhu8Rlv5Y3niDGDf3H4HdfrXHAIQoOE',
    appId: '1:99718845829:android:985b2981689234224ba0ec',
    messagingSenderId: '99718845829',
    projectId: 'jeevan-b42a9',
    storageBucket: 'jeevan-b42a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlW1g0Cf8-AdzO9Lm3dZ04tArcuRnoFw',
    appId: '1:99718845829:ios:6e7cb428b44a17ad4ba0ec',
    messagingSenderId: '99718845829',
    projectId: 'jeevan-b42a9',
    storageBucket: 'jeevan-b42a9.firebasestorage.app',
    iosBundleId: 'com.example.jeevan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlW1g0Cf8-AdzO9Lm3dZ04tArcuRnoFw',
    appId: '1:99718845829:ios:6e7cb428b44a17ad4ba0ec',
    messagingSenderId: '99718845829',
    projectId: 'jeevan-b42a9',
    storageBucket: 'jeevan-b42a9.firebasestorage.app',
    iosBundleId: 'com.example.jeevan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyoFEZfAdjWhSZ-viLaBXGjb4OUr7_XH4',
    appId: '1:99718845829:web:606c5a2cb39d79ab4ba0ec',
    messagingSenderId: '99718845829',
    projectId: 'jeevan-b42a9',
    authDomain: 'jeevan-b42a9.firebaseapp.com',
    storageBucket: 'jeevan-b42a9.firebasestorage.app',
  );
}
